### PR TITLE
Update to latest version of PluginSDK

### PR DESCRIPTION
**Pull request by juicermv**
This updates the mod to the latest version of PluginSDK

### CODE REVIEW

**Comment by juicermv** [comment]
May I ask why this was closed? You literally can't compile the mod without this fix

**Comment by gennariarmando** [comment]
Get latest plugin-sdk to make this compile correctly.

**Comment by juicermv** [comment]
Dude. I have the latest version. `CFont::GetStringWidth` has been updated so it takes three arguments and not two.

**Comment by gennariarmando** [comment]
No it doesn’t.

**Comment by juicermv** [comment]
It does, but there's a default value for the third parameter. For some odd reason MSVC doesn't recognize this. Oh well.

**Pull request closed without merging**
